import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} dark:bg-neutral-900 dark:text-neutral-50 text-zinc-800 w-[32%] max-[1200px]:w-[85%] max-[500px]:w-[91%] m-auto h-screen py-5 `}
      >
        {children}
      </body>
    </html>
  );
}
